/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_lwjgl_opencl_CL */

#ifndef _Included_org_lwjgl_opencl_CL
#define _Included_org_lwjgl_opencl_CL
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_lwjgl_opencl_CL
 * Method:    nCreate
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opencl_CL_nCreate
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_lwjgl_opencl_CL
 * Method:    nCreateDefault
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opencl_CL_nCreateDefault
  (JNIEnv *, jclass);

/*
 * Class:     org_lwjgl_opencl_CL
 * Method:    nDestroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opencl_CL_nDestroy
  (JNIEnv *, jclass);

/*
 * Class:     org_lwjgl_opencl_CL
 * Method:    ngetFunctionAddress
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_lwjgl_opencl_CL_ngetFunctionAddress
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_lwjgl_opencl_CL
 * Method:    getHostBuffer
 * Signature: (JI)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_org_lwjgl_opencl_CL_getHostBuffer
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_lwjgl_opencl_CL
 * Method:    resetNativeStubs
 * Signature: (Ljava/lang/Class;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opencl_CL_resetNativeStubs
  (JNIEnv *, jclass, jclass);

#ifdef __cplusplus
}
#endif
#endif
