/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_lwjgl_input_Cursor_CursorElement */

#ifndef _Included_org_lwjgl_input_Cursor_CursorElement
#define _Included_org_lwjgl_input_Cursor_CursorElement
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
