name: Feature Request / 功能请求
description: |
  Propose new features for Fold Craft Launcher.
  为 Fold Craft Launcher 提出新功能。
labels: enhancement/增强
body:
- type: markdown
  attributes:
    value: |
      Make sure to check the issues list for duplicates before submitting!
      提交前，请务必检查问题列表中的重复项！
- type: checkboxes
  id: checks
  attributes:
    label: Before making issue / 在发布提问之前...
    options:
    - label: I understand this is a request, not a wish. 我明白这是在提出请求而不是在许愿。
      required: true
    - label: I have searched for existing issues. 我已经搜索了现有的 issues。
      required: true
- type: textarea
  id: "feature"
  attributes:
    label: Description / 描述
    description: |
      Describe in detail the new features you would like to add.
      详细描述你要添加的新功能。
  validations:
    required: true
- type: textarea
  id: "reason"
  attributes:
    label: Why / 原因
    description: |
      Describe the benefits of this feature and why.
      描述此功能的好处及其原因。
  validations:
    required: true
- type: textarea
  id: "solution"
  attributes:
    label: Proposed Solution (optional) / 设想方案（可选）
    description: |
      If you have an idea of how to implement this feature, describe it here.
      如果你对如何实现此功能有想法，请在这里描述。
