/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_lwjgl_opengl_FCLPbufferPeerInfo */

#ifndef _Included_org_lwjgl_opengl_FCLPbufferPeerInfo
#define _Included_org_lwjgl_opengl_FCLPbufferPeerInfo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_lwjgl_opengl_FCLPbufferPeerInfo
 * Method:    nInitHandle
 * Signature: (JLjava/nio/ByteBuffer;IILorg/lwjgl/opengl/PixelFormat;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_FCLPbufferPeerInfo_nInitHandle
  (JNIEnv *, jclass, jlong, jobject, jint, jint, jobject);

/*
 * Class:     org_lwjgl_opengl_FCLPbufferPeerInfo
 * Method:    nDestroy
 * Signature: (Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_FCLPbufferPeerInfo_nDestroy
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
