/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_lwjgl_opengl_FCLDisplayPeerInfo */

#ifndef _Included_org_lwjgl_opengl_FCLDisplayPeerInfo
#define _Included_org_lwjgl_opengl_FCLDisplayPeerInfo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_lwjgl_opengl_FCLDisplayPeerInfo
 * Method:    initDefaultPeerInfo
 * Signature: (JLjava/nio/ByteBuffer;Lorg/lwjgl/opengl/PixelFormat;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_FCLDisplayPeerInfo_initDefaultPeerInfo
  (JNIEnv *, jclass, jlong, jobject, jobject);

/*
 * Class:     org_lwjgl_opengl_FCLDisplayPeerInfo
 * Method:    initDrawable
 * Signature: (Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_FCLDisplayPeerInfo_initDrawable
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
