/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_lwjgl_opengl_FCLKeyboard */

#ifndef _Included_org_lwjgl_opengl_FCLKeyboard
#define _Included_org_lwjgl_opengl_FCLKeyboard
#ifdef __cplusplus
extern "C" {
#endif
#undef org_lwjgl_opengl_FCLKeyboard_KEYBOARD_BUFFER_SIZE
#define org_lwjgl_opengl_FCLKeyboard_KEYBOARD_BUFFER_SIZE 50L
#ifdef __cplusplus
}
#endif
#endif
