/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_lwjgl_opengl_FCLPeerInfo */

#ifndef _Included_org_lwjgl_opengl_FCLPeerInfo
#define _Included_org_lwjgl_opengl_FCLPeerInfo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_lwjgl_opengl_FCLPeerInfo
 * Method:    createHandle
 * Signature: ()Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_org_lwjgl_opengl_FCLPeerInfo_createHandle
  (JNIEnv *, jclass);

/*
 * Class:     org_lwjgl_opengl_FCLPeerInfo
 * Method:    nGetDisplay
 * Signature: (Ljava/nio/ByteBuffer;)J
 */
JNIEXPORT jlong JNICALL Java_org_lwjgl_opengl_FCLPeerInfo_nGetDisplay
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_lwjgl_opengl_FCLPeerInfo
 * Method:    nGetDrawable
 * Signature: (Ljava/nio/ByteBuffer;)J
 */
JNIEXPORT jlong JNICALL Java_org_lwjgl_opengl_FCLPeerInfo_nGetDrawable
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
