/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_lwjgl_opengl_FCLMouse */

#ifndef _Included_org_lwjgl_opengl_FCLMouse
#define _Included_org_lwjgl_opengl_FCLMouse
#ifdef __cplusplus
extern "C" {
#endif
#undef org_lwjgl_opengl_FCLMouse_WHEEL_SCALE
#define org_lwjgl_opengl_FCLMouse_WHEEL_SCALE 120L
#undef org_lwjgl_opengl_FCLMouse_Button1
#define org_lwjgl_opengl_FCLMouse_Button1 1L
#undef org_lwjgl_opengl_FCLMouse_Button2
#define org_lwjgl_opengl_FCLMouse_Button2 2L
#undef org_lwjgl_opengl_FCLMouse_Button3
#define org_lwjgl_opengl_FCLMouse_Button3 3L
#undef org_lwjgl_opengl_FCLMouse_Button4
#define org_lwjgl_opengl_FCLMouse_Button4 4L
#undef org_lwjgl_opengl_FCLMouse_Button5
#define org_lwjgl_opengl_FCLMouse_Button5 5L
#undef org_lwjgl_opengl_FCLMouse_Button6
#define org_lwjgl_opengl_FCLMouse_Button6 6L
#undef org_lwjgl_opengl_FCLMouse_Button7
#define org_lwjgl_opengl_FCLMouse_Button7 7L
#undef org_lwjgl_opengl_FCLMouse_Button8
#define org_lwjgl_opengl_FCLMouse_Button8 8L
#undef org_lwjgl_opengl_FCLMouse_Button9
#define org_lwjgl_opengl_FCLMouse_Button9 9L
#undef org_lwjgl_opengl_FCLMouse_ButtonPress
#define org_lwjgl_opengl_FCLMouse_ButtonPress 4L
#undef org_lwjgl_opengl_FCLMouse_ButtonRelease
#define org_lwjgl_opengl_FCLMouse_ButtonRelease 5L
/*
 * Class:     org_lwjgl_opengl_FCLMouse
 * Method:    nGetWindowHeight
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_lwjgl_opengl_FCLMouse_nGetWindowHeight
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_lwjgl_opengl_FCLMouse
 * Method:    nGetWindowWidth
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_lwjgl_opengl_FCLMouse_nGetWindowWidth
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_lwjgl_opengl_FCLMouse
 * Method:    nGetButtonCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_lwjgl_opengl_FCLMouse_nGetButtonCount
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
