/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_lwjgl_FCLSysImplementation */

#ifndef _Included_org_lwjgl_FCLSysImplementation
#define _Included_org_lwjgl_FCLSysImplementation
#ifdef __cplusplus
extern "C" {
#endif
#undef org_lwjgl_FCLSysImplementation_JNI_VERSION
#define org_lwjgl_FCLSysImplementation_JNI_VERSION 23L
#ifdef __cplusplus
}
#endif
#endif
