name: Release

on:
  push:
    tags:
      - "*"

jobs:
  build:
    uses: ./.github/workflows/build.yml
    secrets: inherit

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download apks
        uses: actions/download-artifact@v6
        with:
          path: apks

      - name: Release
        uses: softprops/action-gh-release@v3
        with:
          token: ${{ secrets.TOKEN }}
          files: apks/**/*.apk
          body_path: CHANGELOG.md
